apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- devm-1.yaml
- devm-2.yaml
- devm-3.yaml
- devm-4.yaml
- devm-5.yaml
- devm-6.yaml
- devm-7.yaml
- devm-8.yaml
- devm-9.yaml
- devm-10.yaml

# NOTE
# ----
# 1. Required attached storage. For the above PVs to work, we need 4 dirs
# on host `devm` created like this:
#
#     $ sudo mkdir -p /mnt/k8s-data/d{1..10}
#     $ sudo chmod -R 777 /mnt/k8s-data
#
# Ideally each of them should actually be backed by a disk or a partition,
# but if you're in a hurry and don't care about proper storage, just running
# the above commands will do.
