apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: "http-virtual-service"
spec:
  gateways:
  - default-gateway
  hosts:
  - "reccommender.argo"
  http:
  - match:
    - port: 80
    route:
    - destination:
        host: argocd-server.argocd.svc.cluster.local
        port:
          number: 80
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: "ui-virtualservice"
spec:
  gateways:
  - default-gateway
  hosts:
  - "reccommender.ui"
  http:
  - match:
    - port: 80
    route:
    - destination:
        host: reccommenderui-service.default.svc.cluster.local
        port:
          number: 3000
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: "reccommender-virtualservice"
spec:
  gateways:
  - default-gateway
  hosts:
  - "reccommender.back"
  http:
  - match:
    - port: 80
    route:
    - destination:
        host: reccommender-service.default.svc.cluster.local
        port:
          number: 8082
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: "datapolicy-virtualservice"
spec:
  gateways:
  - default-gateway
  hosts:
  - "reccommender.datapolicy"
  http:
  - match:
    - port: 80
    route:
    - destination:
        host: datapolicy-service.default.svc.cluster.local
        port:
          number: 8075
# NOTE
# 1. URL rewriting. We use overlapping prefixes to make sure `/x`, `/x/`
# and `/x/p` get rewritten to `/`, `/` and `/p` respectively. Istio will
# moan about it, e.g.
#
#   Warning: virtualService rule #3 match #0 of prefix /argocd/ is not used
#           (duplicate/overlapping match in rule #1 of prefix /argocd on #3)
#
# But if you take out either URI prefix match, things will break---e.g.
# try navigating to the Argo CD UI.
# See:
# - https://github.com/istio/istio/issues/8076
#
# 2. Keycloak base path. Keycloak is configured with an HTTP rel path of
# `/keycloak`, which makes every URL in the UI is relative to `/keycloak`.
# So we don't need a rewrite rule in this case.
#
