apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: "http-virtual-service"
spec:
  gateways:
  - "default-gateway"
  hosts:
  - "*"
  http:
  - match:  # NOTE (1)
    - uri:
        prefix: /argocd/
    - uri:
        prefix: /argocd
    rewrite:
      uri: /
    route:
    - destination:
        host: argocd-server.argocd.svc.cluster.local
        port:
          number: 80
  - match:  # NOTE (1)
    - uri:
        prefix: /httpbin/
    - uri:
        prefix: /httpbin
    rewrite:
      uri: /
    route:
    - destination:
        host: httpbin.default.svc.cluster.local
        port:
          number: 8000
  - match:  # NOTE (2)
    - uri:
        prefix: /back
    route:
    - destination:
        host: reccommender-service.default.svc.cluster.local
        port:
          number: 8082
  - match:  # NOTE (2)
    - uri:
        prefix: /datapolicy
    route:
    - destination:
        host: datapolicy-service.default.svc.cluster.local
        port:
          number: 8075
  - match:  # NOTE (2)
    - uri:
        prefix: /ui
    route:
    - destination:
        host: reccommenderui-service.default.svc.cluster.local
        port:
          number: 3000
  - match:  # NOTE (1)
    - uri:
        prefix: /minio/
    - uri:
        prefix: /minio
    rewrite:
      uri: /
    route:
    - destination:
        host: minio.minio-operator.svc.cluster.local
        port:
          number: 80