apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: "argocd-gateway"
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:                                    # <----- All hosts we want to be responsible for
     - "reccommender.localdomain"
    port:
      name: http
      number: 80
      protocol: HTTP
---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: "ui-gateway"
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:                                    # <----- All hosts we want to be responsible for
     - "reccommender.localdomain"
    port:
      name: http
      number: 3000
      protocol: HTTP
---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: "back-gateway"
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:                                    # <----- All hosts we want to be responsible for
     - "reccommender.localdomain"
    port:
      name: http
      number: 8080
      protocol: HTTP
---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: "datapolicy-gateway"
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:                                    # <----- All hosts we want to be responsible for
     - "reccommender.localdomain"
    port:
      name: http
      number: 8075
      protocol: HTTP