apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: "default-gateway"
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:                                  
     - "*.reccommender.io"
    port:
      name: http
      number: 80
      protocol: HTTP
 
