apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: "default-gateway"
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:                                  
     - "reccommender.argo"
    port:
      name: argo
      number: 80
      protocol: HTTP
  - hosts:                                    
     - "reccommender.ui"
    port:
      name: ui
      number: 3000
      protocol: HTTP
  - hosts:                                    
     - "reccommender.back"
    port:
      name: back
      number: 8082
      protocol: HTTP
  - hosts:                                    
     - "reccommender.datapolicy"
    port:
      name: datapolicy
      number: 8075
      protocol: HTTP
