apiVersion: v1
kind: Secret
metadata:
  name: reccommenderui-secret
type: Opaque
data:
  REACT_APP_AMON_URL: aHR0cDovL2xvY2FsaG9zdDo4MDc1Cg==
  REACT_APP_DEFAULT_TENANT: ZGVmYXVsdAo=
  REACT_APP_DEFAULT_PATH: Lwo=
  REACT_APP_RECOMMENDER: aHR0cDovL2xvY2FsaG9zdDo4MDgwCg==
