apiVersion: v1
kind: Secret
metadata:
  name: datapolicy-secret
type: Opaque
data:
  CORS_ALLOWED_ORIGINS: Kgo=
  CORS_ALLOWED_METHODS: Kgo=
  CORS_ALLOWED_HEADERS: Kgo=
  DB_TYPE: cG9zdGdyZXMK
  DB_HOST: cG9zdGdyZXMtc2VydmljZQo=
  KEYCLOACK_ENABLED: ZmFsc2UK