apiVersion: apps/v1
kind: Deployment
metadata:
  name: datapolicy-deployment
  labels:
    app: datapolicy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: datapolicy
  template:
    metadata:
      labels:
        app: datapolicy
    spec:
      containers:
      - name: datapolicy
        image: orchestracities/amon-management-api:dev-test
        resources:
          requests:
            memory: "128Mi"
            cpu: "500m"
          limits:
            memory: "256Mi"
            cpu: "1000m"
        ports:
        - containerPort: 8075
        env:
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: datapolicy-secret-clear
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-users
              key: postgres.password
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: postgres-users
              key: postgres.db
        - name: CORS_ALLOWED_ORIGINS
          valueFrom:
            secretKeyRef:
              name: datapolicy-secret-clear
              key: CORS_ALLOWED_ORIGINS
        - name: CORS_ALLOWED_METHODS
          valueFrom:
            secretKeyRef:
              name: datapolicy-secret-clear
              key: CORS_ALLOWED_METHODS
        - name: CORS_ALLOWED_HEADERS
          valueFrom:
            secretKeyRef:
              name: datapolicy-secret-clear
              key: CORS_ALLOWED_HEADERS
        - name: DB_TYPE
          valueFrom:
            secretKeyRef:
              name: datapolicy-secret-clear
              key: DB_TYPE
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: datapolicy-secret-clear
              key: DB_HOST
        - name: KEYCLOACK_ENABLED
          valueFrom:
            secretKeyRef:
              name: datapolicy-secret
              key: KEYCLOACK_ENABLED
---
apiVersion: v1
kind: Service
metadata:
  name: datapolicy-service
spec:
  type: NodePort
  selector:
    app: datapolicy
  ports:
    - protocol: TCP
      port: 8075
      targetPort: 8075
      nodePort: 8075