apiVersion: v1
kind: Secret
metadata:
  name: datapolicy-secret
  namespace: default
type: Opaque
data:
  CORS_ALLOWED_ORIGINS: Kgo=
  CORS_ALLOWED_METHODS: Kgo=
  CORS_ALLOWED_HEADERS: Kgo=
  DB_TYPE: cG9zdGdyZXMK
  DB_HOST: cG9zdGdyZXMtc2VydmljZS5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FsCg==
  DB_USER: cG9zdGdyZXMK
  KEYCLOACK_ENABLED: ZmFsc2UK
  postgres.user: cG9zdGdyZXMK